export const USER_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_A_STRING: 'Name must be a string',
  NAME_LENGTH_MUST_BE_FROM_6_TO_100:
    'Name length must be greater than or equal to 6 characters long and less than or equal to 100 characters',
  EMAIL_ALREADY_EXISTENT_ERROR: 'Email already exists',
  EMAIL_IS_NOT_EXISTENT_ERROR: 'Email is not existed',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_INVALID: 'Invalid email',
  PASSWORD_REQUIRED: 'Password is required',
  PASSWORD_MUST_BE_A_STRING: 'Password must be a string',
  PASSWORD_LENGTH: 'Password must be at maximum 16 characters',
  WRONG_PASSWORD: 'Wrong password',
  CHANGE_PASSWORD_SUCCESS: 'Change password successfully',
  PASSWORD_MUST_BE_STRONG: 'Password must be at least 1 lower case, 1 upper case, 1 number and 1 symbol',
  DOB_MUST_BE_ISO_STRING: 'Dob must be a valid ISO string ',
  LOGIN_SUCCESS: 'Login success',
  LOGIN_ERROR: 'Login error',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  UNAUTHORIZED: 'Unauthorized',
  REFRESH_TOKEN_NOT_VALID: ' Refresh token is not valid',
  LOGOUT_SUCCESS: 'Logout success',
  REGISTER_SUCCESS: 'Register success',
  USER_NOT_FOUND: 'User not found',
  EMAIL_VERIFIED: 'Email already verified',
  EMAIL_VERIFY_SUCCESS: 'Email successfully verified',
  RESEND_VERIFY_EMAIL_SUCCESS: 'Resend email verification successfully',
  CHECK_EMAIL_TO_RESET_PASSWORD: 'Check email to reset password',
  FORGOT_PASSWORD_TOKEN_REQUIRED: 'Forgot password token is required',
  FORGOT_PASSWORD_TOKEN_NOT_VALID: 'Forgot password token is not valid',
  VERIFY_FORGOT_PASSWORD_SUCCESS: 'Forgot password verified successfully',
  RESET_PASSWORD_SUCCESS: 'Reset password successfully',
  USER_NOT_VERIFIED: 'User has not been verified yet',
  BIO_MUST_BE_A_STRING: 'Bio must be a string',
  BIO_LENGTH: 'Bio  must be from 1 to 255 characters',
  LOCATION_MUST_BE_A_STRING: 'LOCATION must be a string',
  LOCATION_LENGTH: 'LOCATION  must be from 1 to 255 characters',
  WEBSITE_MUST_BE_A_STRING: 'WEBSITE must be a string',
  WEBSITE_LENGTH: 'WEBSITE  must be from 1 to 255 characters',
  USERNAME_MUST_BE_A_STRING: 'USERNAME must be a string',
  USERNAME_LENGTH: 'USERNAME  must be from 1 to 50 characters',
  USERNAME_INVALID:
    'username must be 4-15 characters long and contain only letters, numers, underscores, not only numbers',
  USERNAME_EXISTED: 'username already exists',
  IMAGE_PATH_MUST_BE_A_STRING: 'IMAGE PATH must be a string',
  IMAGE_PATH_LENGTH: 'IMAGE PATH  must be from 1 to 255 characters',
  FOLLOW_SUCCESS: 'follow success',
  FOLLOWED: 'followed before',
  NOT_FOLLOWED: "Hasn't followed before",
  UNFOLLOW_SUCCESS: 'Unfollow success',
  GMAIL_NOT_VERIFIED: 'Gmail not verified'
}

export const TWEET_MESSAGES = {
  INVALID_TYPE: 'Invalid type',
  INVALID_AUDIENCE: 'Invalid audience',
  SHOULD_BE_NO_PARENT: 'Type tweet so parent_id should be null',
  PARENT_ID_INVALID: 'parent_id is not valid',
  CONTENT_MUST_BE_EMPTY: 'Content must be empty',
  CONTENT_INVALID: 'Content is not valid',
  HASHTAGS_MUST_BE_STRING_ARRAY: 'hashtags must be a string array',
  MENTIONS_MUST_BE_OBJECT_ID_ARRAY: 'mentions must be a objectId array',
  MEDIA_INVALID: 'Media is not valid'
}
