export const USER_MESSAGES = {
  VALIDATION_ERROR: 'Validation error',
  NAME_IS_REQUIRED: 'Name is required',
  NAME_MUST_BE_A_STRING: 'Name must be a string',
  NAME_LENGTH_MUST_BE_FROM_6_TO_100:
    'Name length must be greater than or equal to 6 characters long and less than or equal to 100 characters',
  EMAIL_ALREADY_EXISTENT_ERROR: 'Email already exists',
  EMAIL_IS_NOT_EXISTENT_ERROR: 'Email is not existed',
  EMAIL_IS_REQUIRED: 'Email is required',
  EMAIL_INVALID: 'Invalid email',
  PASSWORD_REQUIRED: 'Password is required',
  PASSWORD_MUST_BE_A_STRING: 'Password must be a string',
  PASSWORD_LENGTH: 'Password must be at maximum 16 characters',
  PASSWORD_MUST_BE_STRONG: 'Password must be at least 1 lower case, 1 upper case, 1 number and 1 symbol',
  DOB_MUST_BE_ISO_STRING: 'Dob must be a valid ISO string ',
  LOGIN_SUCCESS: 'Login success',
  LOGIN_ERROR: 'Login error',
  ACCESS_TOKEN_IS_REQUIRED: 'Access token is required',
  REFRESH_TOKEN_IS_REQUIRED: 'Refresh token is required',
  EMAIL_VERIFY_TOKEN_IS_REQUIRED: 'Email verify token is required',
  UNAUTHORIZED: 'Unauthorized',
  REFRESH_TOKEN_NOT_VALID: ' Refresh token is not valid',
  LOGOUT_SUCCESS: 'Logout success',
  USER_NOT_FOUND: 'User not found',
  EMAIL_VERIFIED: 'Email already verified',
  EMAIL_VERIFY_SUCCESS: 'Email successfully verified'
}
